baseurl = "http://blog.zecure.org"
title = "Zecure"
author = "Hendrik Buchwald"
canonifyurls = true
paginate = 3

[params]
  DateForm = "Mon, Jan 2, 2006"
  Twitter = "zecureit"
  Github = "zecure"
  GoogleAnalyticsUserID = "UA-58987297-3"
  SyntaxHighlightTheme = "github.min.css"

[Indexes]
  tag ="tags"
