baseurl = "https://blog.zecure.org"
title = "Zecure"
author = "Hendrik Buchwald"
canonifyurls = true
paginate = 3

[params]
  DateForm = "Mon, Jan 2, 2006"
  Twitter = "zecureit"
  Github = "zecure"

[Indexes]
  tag ="tags"
